// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvAQsBofmTqzhglEQ92pQFSWa2SzjAPcQ',
    appId: '1:961948037717:web:f5f70f6d79574896f01adc',
    messagingSenderId: '961948037717',
    projectId: 'auth-test-6bdb9',
    authDomain: 'auth-test-6bdb9.firebaseapp.com',
    storageBucket: 'auth-test-6bdb9.appspot.com',
    measurementId: 'G-B2J65E9E9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbwM9iyH32eSrt9nawY7eDstDvdP1SjsI',
    appId: '1:961948037717:android:98cd458b453b9bbbf01adc',
    messagingSenderId: '961948037717',
    projectId: 'auth-test-6bdb9',
    storageBucket: 'auth-test-6bdb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgM9e0AVv3bM_dRIB2BGzFpjA_dy40HDQ',
    appId: '1:961948037717:ios:5bc78d1d0281c23df01adc',
    messagingSenderId: '961948037717',
    projectId: 'auth-test-6bdb9',
    storageBucket: 'auth-test-6bdb9.appspot.com',
    iosClientId: '961948037717-0qsi1c78n3c2s22gfbat64m5qnt3pdpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalYearProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgM9e0AVv3bM_dRIB2BGzFpjA_dy40HDQ',
    appId: '1:961948037717:ios:5bc78d1d0281c23df01adc',
    messagingSenderId: '961948037717',
    projectId: 'auth-test-6bdb9',
    storageBucket: 'auth-test-6bdb9.appspot.com',
    iosClientId: '961948037717-0qsi1c78n3c2s22gfbat64m5qnt3pdpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalYearProject',
  );
}
